#!/bin/bash
BuildModeName=""
sop="Sequence"
pbop="Balance"
if [ $BuildMode -eq 0 ]
 then
   BuildModeName="LeafToRoot"
 else
   if [ $BuildMode -eq 1 ]
     then
       BuildModeName="RootToLeaf"
     else
       BuildModeName="Parallel"
   fi
fi
echo $BuildModeName
echo ""
echo ""
curCmd=""
case $DataType in
   vector)curCmd="./cGeDBIT --runOption build --buildMode $BuildMode --indexName vector_"$Size"_"$BuildModeName"_v2_f3_m100 --n uniformvector-20dim-1m.txt --v 2 --f 3 --t vector --e MVPIndex --psm fft --dpm PivotWise --sop "$sop" --pbop "$pbop" --tR 0.4 --m 100 --init $Size --F $Size --s 2000 --dim 20 --res results_vector_build_"$Size"i_"$BuildModeName"_fft_balanced_MVPIndex_v2_f3_m100_dim20.txt";;
   string)curCmd="./cGeDBIT --runOption build --buildMode $BuildMode --indexName string_"$Size"_"$BuildModeName"_v2_f3_m100 --n English.dic --v 2 --f 3 --t string --e MVPIndex --psm fft --dpm PivotWise --sop "$sop" --pbop "$pbop" --tR 2 --m 100 --init $Size --F $Size --s 2000 --dim 2 --res results_string_build_"$Size"i_"$BuildModeName"_fft_balanced_MVPIndex_v2_f3_m100_dim2.txt";;
   image)curCmd="./cGeDBIT --runOption build --buildMode $BuildMode --indexName image_"$Size"_"$BuildModeName"_v2_f3_m100 --n allfeas.dat --v 2 --f 3 --t image --e MVPIndex --psm fft --dpm PivotWise --sop "$sop" --pbop "$pbop" --tR 0.1 --m 100 --init $Size --F $Size --s 2000 --dim 66 --res results_image_build_"$Size"i_"$BuildModeName"_fft_balanced_MVPIndex_v2_f3_m100_dim66.txt";;
   dna)curCmd="./cGeDBIT --runOption build --buildMode $BuildMode --indexName dna_"$Size"_"$BuildModeName"_v2_f3_m100 --n arab1.con --v 2 --f 3 --t dna --e MVPIndex --psm fft --dpm PivotWise --sop "$sop" --pbop "$pbop" --tR 2 --m 100 --init $Size --F $Size --s 2000 --frag 18 --res results_dna_build_"$Size"i_"$BuildModeName"_fft_balanced_MVPIndex_v2_f3_m100_frag18.txt";;
   peptide)curCmd="./cGeDBIT --runOption build --buildMode $BuildMode --indexName peptide_"$Size"_"$BuildModeName"_v2_f3_m100 --n nrall.fasta --v 2 --f 3 --t peptide --e MVPIndex --psm fft --dpm PivotWise --sop "$sop" --pbop "$pbop" --tR 2 --m 100 --init $Size --F $Size --s 2000 --frag 6 --res results_peptide_build_"$Size"i_"$BuildModeName"_fft_balanced_MVPIndex_v2_f3_m100_frag6.txt";;
esac
echo "Current Task : Build Index ( Size:$Size,BuildMode:$BuildMode )"
echo "Current Command:$curCmd"
echo ""
startTime=`date +%T`
startData=`date +%D`
echo "Build start on $startTime $startData"
echo "==============================================="
echo ""
cd ../Compile/
echo "Build Processing......"
$curCmd
echo ""
cd ../Shell/
echo "================================================"
endTime=`date +%T`
endData=`date +%D`
echo "Build Ended on $endTime $endData"
echo ""
echo ""
echo ""
